// import { type Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export const meta: MetaFunction<typeof loader> = (args) => {
//   const { data, params } = args;
//   const { id } = params;
//   return [
//     { title: "YT To YT No Cookie" },
//     { name: "description", content: "Simple little website that takes a YouTube URL (Share and Embed URL's and Video ID's are also supported) and turns it into a YouTube nocookie URL" },
//     { property: "og:url", content: `${data?.siteUrl}/video/${id}` },
//     { name: "og:title", content: "YT To YT No Cookie" },
//     { name: "og:description", content: "Simple little website that takes a YouTube URL (Share and Embed URL's and Video ID's are also supported) and turns it into a YouTube nocookie URL" },
//     { property: "og:image", content: `${data?.siteUrl}/img/${id}?id=${id}` },
//     { name: "twitter:card", content: "summary_large_image" },
//     { name: "twitter:creator", content: "@altie122" },
//     { name: "twitter:site", content: "@altie122" },
//     { name: "twitter:title", content: "YT To YT No Cookie" },
//     { name: "twitter:description", content: "Simple little website that takes a YouTube URL (Share and Embed URL's and Video ID's are also supported) and turns it into a YouTube nocookie URL" },
//     { name: "twitter:image", content: `${data?.siteUrl}/img/${id}?id=${id}` },

//   ];
// };

export default function VideoPage({ params }: { params: { id: string } }) {
  const id = params.id;
  const URL = "https://www.youtube-nocookie.com/embed/" + id;
  return (
    <div className="container mx-auto">
      <h2 className="text-lg no-underline hover:underline md:text-2xl">
        {URL}
      </h2>
      <h1 className="text-lg">Embed:</h1>
      <iframe
        className="mx-auto aspect-video w-full rounded-2xl"
        title="embed"
        src={URL}
        allowFullScreen
      ></iframe>
    </div>
  );
}
